name: ICCF Chess Notifier

on:
  schedule:
    - cron: '13,33,53 * * * *'
  workflow_dispatch:

jobs:
  check-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v4

      - name: Skonfiguruj środowisko Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Zainstaluj Stockfisha
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish

      - name: Zainstaluj zależności Pythona
        run: |
          pip install -r requirements.txt

      - name: Uruchom analizator
        env:
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ICCF_USERNAME: ${{ secrets.ICCF_USERNAME }}
          STOCKFISH_PATH: "/usr/games/stockfish"
        run: |
          python main.py
